-- Activity catalogue: 60 activities, 5 categories x 4 levels x 3 variants.
--
-- Content limits from docs/07 §5, none of them negotiable:
--   * daily stimulation at home, never a clinical therapy protocol
--   * no licensed therapy method is named as though the app delivered it
--   * no promise that anything will be reached in any timeframe
--   * nothing involving restraint, punishment, or withholding a response
--   * household objects only. Bab II of the proposal is about the cost of
--     therapy, so an activity that requires buying equipment argues against
--     the product it belongs to
--   * steps address the child by name, never "si anak" or "pasien"
--
-- {nama} is substituted with the child's nickname when the step is rendered.
-- The catalogue is shared by every account, so it can never hold a real name.
--
-- Levels are a starting point that the adaptation engine corrects from real
-- responses within days. They are not an assessment of the child.

insert into aktivitas
  (kategori, tingkat, judul, tujuan, durasi_menit, alat, langkah,
   saran_lingkungan, cocok_untuk_komunikasi)
values

-- ============================================================ KOMUNIKASI ==

('komunikasi', 1, 'Menirukan bunyi benda saat bermain',
 'Melatih {nama} menirukan bunyi yang ia dengar, sebagai langkah awal menirukan kata.',
 6, '{"Mobil mainan","Sendok","Gelas plastik"}',
 '[{"urutan":1,"teks":"Duduk sejajar dengan {nama}, bukan di seberang meja."},
   {"urutan":2,"teks":"Jalankan mobil mainan sambil mengucap brmm satu kali."},
   {"urutan":3,"teks":"Tunggu lima detik tanpa bicara."},
   {"urutan":4,"teks":"Jika {nama} menirukan, ulangi bunyi itu bersama-sama."}]',
 'Matikan televisi dan radio agar hanya ada satu sumber bunyi di ruangan.',
 '{belum_verbal,beberapa_kata}'),

('komunikasi', 1, 'Memilih dua benda dengan menunjuk',
 'Melatih {nama} menyampaikan pilihan dengan menunjuk ketika kata belum tersedia.',
 6, '{"Dua jenis buah","Piring"}',
 '[{"urutan":1,"teks":"Letakkan dua benda di depan {nama} dengan jarak satu telapak tangan."},
   {"urutan":2,"teks":"Sebutkan kedua namanya sekali, lalu diam."},
   {"urutan":3,"teks":"Tunggu sampai {nama} menunjuk, melirik, atau meraih salah satu."},
   {"urutan":4,"teks":"Berikan yang ia pilih, dan sebutkan namanya satu kali."}]',
 'Kurangi benda lain di atas meja sampai hanya dua pilihan yang terlihat.',
 '{belum_verbal,beberapa_kata}'),

('komunikasi', 1, 'Menyebut nama anggota keluarga dari foto',
 'Melatih {nama} mengaitkan wajah yang dikenal dengan namanya.',
 7, '{"Foto keluarga di ponsel atau cetak"}',
 '[{"urutan":1,"teks":"Pilih tiga foto orang yang paling sering {nama} temui."},
   {"urutan":2,"teks":"Tunjuk satu foto dan sebutkan namanya sekali."},
   {"urutan":3,"teks":"Tunjuk foto yang sama lagi, lalu tunggu tanpa bicara."},
   {"urutan":4,"teks":"Terima jawaban apa pun, termasuk suku kata pertama saja."}]',
 'Redupkan layar ponsel dan hadap membelakangi jendela agar tidak silau.',
 '{belum_verbal,beberapa_kata}'),

('komunikasi', 2, 'Menamai benda di meja makan',
 'Melatih {nama} menyebutkan nama benda yang sedang ia lihat, tanpa didahului pertanyaan.',
 10, '{"Piring","Gelas","Sendok"}',
 '[{"urutan":1,"teks":"Duduk sejajar dengan {nama}, bukan di seberang meja."},
   {"urutan":2,"teks":"Tunjuk satu benda dan tunggu lima detik tanpa bicara."},
   {"urutan":3,"teks":"Jika {nama} belum merespons, sebutkan namanya sekali dengan jelas."},
   {"urutan":4,"teks":"Beri jeda, lalu ulangi dengan benda berikutnya."}]',
 'Matikan televisi dan kurangi benda di atas meja menjadi tiga saja.',
 '{beberapa_kata,kalimat_pendek}'),

('komunikasi', 2, 'Meminta bantuan dengan satu kata',
 'Melatih {nama} memakai satu kata untuk meminta, bukan menunggu sampai kesal.',
 10, '{"Toples bertutup rapat","Camilan kesukaan"}',
 '[{"urutan":1,"teks":"Masukkan camilan ke toples dan tutup agak rapat."},
   {"urutan":2,"teks":"Berikan toples kepada {nama} dan tunggu."},
   {"urutan":3,"teks":"Saat {nama} kesulitan, ucapkan buka satu kali, lalu tunggu lima detik."},
   {"urutan":4,"teks":"Bantu segera setelah ia mencoba, walau bunyinya belum jelas."},
   {"urutan":5,"teks":"Hentikan aktivitas sebelum {nama} kehilangan minat."}]',
 'Longgarkan tutup toples supaya usaha yang dibutuhkan lebih kecil.',
 '{beberapa_kata,kalimat_pendek}'),

('komunikasi', 2, 'Menjawab pilihan air atau susu',
 'Melatih {nama} menjawab pertanyaan pilihan dengan kata, bukan hanya menunjuk.',
 10, '{"Dua gelas","Air","Susu"}',
 '[{"urutan":1,"teks":"Angkat dua gelas setinggi mata {nama}."},
   {"urutan":2,"teks":"Tanya air atau susu, lalu diam."},
   {"urutan":3,"teks":"Tunggu lima detik penuh sebelum mengulang."},
   {"urutan":4,"teks":"Berikan yang ia sebut, meski hanya sebagian kata."}]',
 'Pilih waktu ketika {nama} memang sedang haus agar dorongannya alami.',
 '{beberapa_kata,kalimat_pendek}'),

('komunikasi', 3, 'Menyusun kalimat dua kata saat merapikan mainan',
 'Melatih {nama} menggabungkan dua kata menjadi satu permintaan atau keterangan.',
 14, '{"Kotak mainan","Lima mainan"}',
 '[{"urutan":1,"teks":"Duduk bersama {nama} di dekat kotak mainan."},
   {"urutan":2,"teks":"Ambil satu mainan dan ucapkan dua kata, misalnya mobil masuk."},
   {"urutan":3,"teks":"Berikan mainan berikutnya kepada {nama} dan tunggu."},
   {"urutan":4,"teks":"Jika ia menyebut satu kata, ulangi dengan dua kata tanpa mengoreksi."},
   {"urutan":5,"teks":"Selesaikan setelah lima mainan, walau belum semua terucap."}]',
 'Kurangi jumlah mainan menjadi tiga dan pilih yang paling dikenal {nama}.',
 '{kalimat_pendek,lancar}'),

('komunikasi', 3, 'Menceritakan satu kegiatan tadi pagi',
 'Melatih {nama} menyampaikan kejadian yang sudah lewat dengan kalimat pendek.',
 15, '{"Foto kegiatan pagi, jika ada"}',
 '[{"urutan":1,"teks":"Pilih satu kegiatan yang baru saja {nama} lakukan hari ini."},
   {"urutan":2,"teks":"Mulai kalimatnya dan berhenti di tengah, misalnya tadi pagi kita ..."},
   {"urutan":3,"teks":"Tunggu {nama} melanjutkan tanpa menambahkan pertanyaan."},
   {"urutan":4,"teks":"Ulangi kalimat lengkapnya bersama-sama satu kali."}]',
 'Pilih kegiatan yang baru terjadi kurang dari satu jam yang lalu.',
 '{kalimat_pendek,lancar}'),

('komunikasi', 3, 'Bertanya di mana saat mencari benda',
 'Melatih {nama} memakai kata tanya untuk meminta informasi.',
 14, '{"Benda kesukaan","Kain penutup"}',
 '[{"urutan":1,"teks":"Sembunyikan benda kesukaan {nama} di bawah kain saat ia melihat."},
   {"urutan":2,"teks":"Tunggu {nama} mencarinya."},
   {"urutan":3,"teks":"Ucapkan di mana satu kali sebagai contoh, lalu diam."},
   {"urutan":4,"teks":"Tunjukkan bendanya segera setelah ia bertanya atau mencoba bertanya."}]',
 'Sembunyikan benda di tempat yang masih terlihat sebagian.',
 '{kalimat_pendek,lancar}'),

('komunikasi', 4, 'Bergiliran bercerita tentang gambar',
 'Melatih {nama} menyusun beberapa kalimat berurutan dan menunggu giliran bicara.',
 18, '{"Buku bergambar atau foto"}',
 '[{"urutan":1,"teks":"Pilih satu gambar yang ramai isinya."},
   {"urutan":2,"teks":"Anda bercerita satu kalimat, lalu berhenti."},
   {"urutan":3,"teks":"Tunggu {nama} menambahkan satu kalimat."},
   {"urutan":4,"teks":"Lanjutkan bergantian sampai empat putaran."},
   {"urutan":5,"teks":"Tutup dengan mengulang cerita utuh bersama-sama."}]',
 'Pilih gambar dengan latar polos dan tidak lebih dari tiga tokoh.',
 '{lancar}'),

('komunikasi', 4, 'Menjelaskan urutan tiga langkah',
 'Melatih {nama} menyampaikan urutan dengan kata penghubung.',
 18, '{"Bahan membuat minuman","Gelas","Sendok"}',
 '[{"urutan":1,"teks":"Buat minuman sederhana bersama {nama} satu kali."},
   {"urutan":2,"teks":"Minta {nama} menceritakan ulang caranya kepada Anda."},
   {"urutan":3,"teks":"Bantu hanya dengan kata pertama jika ia berhenti."},
   {"urutan":4,"teks":"Lakukan sekali lagi mengikuti urutan yang ia sebutkan."}]',
 'Kurangi menjadi dua langkah dan lakukan sambil bendanya terlihat.',
 '{lancar}'),

('komunikasi', 4, 'Menawarkan bantuan dengan kalimat lengkap',
 'Melatih {nama} memulai percakapan lebih dulu, bukan hanya menjawab.',
 20, '{"Cucian bersih","Keranjang"}',
 '[{"urutan":1,"teks":"Mulai melipat cucian di dekat {nama} tanpa memintanya membantu."},
   {"urutan":2,"teks":"Tunggu sampai ia memperhatikan."},
   {"urutan":3,"teks":"Jika belum ada tawaran, ucapkan contoh kalimatnya satu kali."},
   {"urutan":4,"teks":"Terima bantuan dalam bentuk apa pun yang ia tawarkan."},
   {"urutan":5,"teks":"Sebutkan kembali kalimat tawarannya saat mengucapkan terima kasih."}]',
 'Lakukan di ruangan yang sedang sepi agar tawaran tidak tenggelam.',
 '{lancar}'),

-- =============================================================== MOTORIK ==

('motorik', 1, 'Memindahkan bola besar ke keranjang',
 'Melatih {nama} mengendalikan gerakan lengan dan badan dengan sasaran yang jelas.',
 6, '{"Bola plastik","Keranjang cucian"}',
 '[{"urutan":1,"teks":"Letakkan keranjang sejauh dua langkah dari {nama}."},
   {"urutan":2,"teks":"Berikan bola dan tunjuk keranjangnya."},
   {"urutan":3,"teks":"Biarkan {nama} memilih cara memasukkannya."},
   {"urutan":4,"teks":"Ulangi lima kali, lalu berhenti."}]',
 'Dekatkan keranjang menjadi satu langkah dan pakai bola yang lebih besar.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 1, 'Meremas kertas menjadi bola',
 'Melatih kekuatan genggaman {nama} dengan gerakan satu tangan.',
 5, '{"Kertas bekas","Wadah"}',
 '[{"urutan":1,"teks":"Sobek kertas menjadi lembar seukuran telapak tangan."},
   {"urutan":2,"teks":"Remas satu lembar di depan {nama} sampai menjadi bola."},
   {"urutan":3,"teks":"Berikan satu lembar kepada {nama} dan tunggu."},
   {"urutan":4,"teks":"Kumpulkan bola kertas ke dalam wadah bersama-sama."}]',
 'Pakai kertas yang lebih tipis agar lebih mudah diremas.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 1, 'Berjalan mengikuti garis lakban',
 'Melatih keseimbangan {nama} pada lintasan yang terlihat jelas.',
 7, '{"Lakban kertas","Lantai kosong"}',
 '[{"urutan":1,"teks":"Tempel lakban lurus sepanjang dua meter di lantai."},
   {"urutan":2,"teks":"Berjalan di atasnya satu kali sambil {nama} melihat."},
   {"urutan":3,"teks":"Ajak {nama} berjalan sambil Anda memegang satu tangannya."},
   {"urutan":4,"teks":"Lepaskan pegangan saat ia sudah mantap."}]',
 'Perpendek garis menjadi satu meter dan pilih lantai yang tidak licin.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 2, 'Melompat dua kaki di atas bantal',
 'Melatih {nama} melompat dengan kedua kaki mendarat bersamaan.',
 10, '{"Dua bantal","Lantai kosong"}',
 '[{"urutan":1,"teks":"Letakkan satu bantal di lantai."},
   {"urutan":2,"teks":"Lompati bantal satu kali sambil {nama} melihat."},
   {"urutan":3,"teks":"Pegang kedua tangan {nama} dan lompat bersama."},
   {"urutan":4,"teks":"Kurangi bantuan sampai ia melompat sendiri."},
   {"urutan":5,"teks":"Berhenti setelah delapan lompatan."}]',
 'Gunakan bantal yang lebih tipis dan jangan bertumpuk.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 2, 'Menjepit kapas dengan jemari',
 'Melatih koordinasi jari {nama} untuk gerakan menjepit yang halus.',
 10, '{"Kapas","Dua mangkuk","Jepitan jemuran"}',
 '[{"urutan":1,"teks":"Isi satu mangkuk dengan kapas."},
   {"urutan":2,"teks":"Pindahkan satu kapas ke mangkuk kosong memakai jari."},
   {"urutan":3,"teks":"Berikan giliran kepada {nama}."},
   {"urutan":4,"teks":"Setelah lancar, coba dengan jepitan jemuran."}]',
 'Pakai kapas yang lebih besar dan mangkuk yang lebih lebar.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 2, 'Menuang air antar gelas',
 'Melatih {nama} mengendalikan kemiringan tangan saat menuang.',
 12, '{"Dua gelas","Air","Nampan","Lap"}',
 '[{"urutan":1,"teks":"Letakkan kedua gelas di atas nampan agar tumpahan tertampung."},
   {"urutan":2,"teks":"Isi satu gelas seperempat penuh."},
   {"urutan":3,"teks":"Tuang ke gelas kosong satu kali sambil {nama} melihat."},
   {"urutan":4,"teks":"Berikan giliran kepada {nama} tanpa memegang tangannya."},
   {"urutan":5,"teks":"Bereskan bersama, tumpah adalah bagian dari latihan."}]',
 'Kurangi isi gelas dan pakai gelas bermulut lebar.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 3, 'Menyusun menara dari enam gelas plastik',
 'Melatih ketelitian tangan {nama} saat menumpuk benda ringan.',
 14, '{"Enam gelas plastik","Meja rata"}',
 '[{"urutan":1,"teks":"Susun tiga gelas menjadi menara sambil {nama} melihat."},
   {"urutan":2,"teks":"Bongkar, lalu berikan gelasnya kepada {nama}."},
   {"urutan":3,"teks":"Tambahkan satu gelas setiap kali menaranya berdiri."},
   {"urutan":4,"teks":"Berhenti di enam gelas atau saat {nama} ingin berhenti."}]',
 'Mulai dari tiga gelas dan pilih meja yang tidak goyang.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 3, 'Berjalan jinjit membawa nampan kosong',
 'Melatih keseimbangan {nama} sambil kedua tangan sedang terpakai.',
 14, '{"Nampan kosong"}',
 '[{"urutan":1,"teks":"Tentukan jalur lurus sepanjang tiga meter."},
   {"urutan":2,"teks":"Berjalan jinjit membawa nampan satu kali."},
   {"urutan":3,"teks":"Ajak {nama} melakukannya di sebelah Anda."},
   {"urutan":4,"teks":"Ulangi tiga kali pulang pergi."}]',
 'Berjalan biasa dulu tanpa jinjit, dan perpendek jalurnya.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 3, 'Menggunting garis lurus di kertas',
 'Melatih {nama} membuka dan menutup gunting mengikuti arah garis.',
 15, '{"Gunting ujung tumpul","Kertas bekas","Spidol"}',
 '[{"urutan":1,"teks":"Gambar satu garis lurus tebal di kertas."},
   {"urutan":2,"teks":"Pegang kertasnya, biarkan {nama} yang memegang gunting."},
   {"urutan":3,"teks":"Gunting bersama sampai ujung garis."},
   {"urutan":4,"teks":"Ulangi dengan garis baru sebanyak tiga kali."}]',
 'Gambar garis lebih tebal dan potong kertas menjadi lebih pendek.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 4, 'Melempar dan menangkap bola bergantian',
 'Melatih {nama} mengatur waktu gerakan tangan terhadap benda yang bergerak.',
 18, '{"Bola plastik ukuran sedang"}',
 '[{"urutan":1,"teks":"Berdiri berhadapan sejauh dua langkah."},
   {"urutan":2,"teks":"Lempar bola pelan setinggi dada {nama}."},
   {"urutan":3,"teks":"Tunggu ia melempar balik tanpa memberi aba-aba."},
   {"urutan":4,"teks":"Mundur satu langkah setiap lima tangkapan berhasil."},
   {"urutan":5,"teks":"Berhenti di jarak yang masih menyenangkan."}]',
 'Perpendek jarak dan gunakan bola yang lebih besar serta lebih lambat.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 4, 'Meronce manik besar menjadi gelang',
 'Melatih koordinasi dua tangan {nama} pada gerakan yang berurutan.',
 18, '{"Manik berlubang besar","Tali sepatu bekas"}',
 '[{"urutan":1,"teks":"Ikat simpul di ujung tali agar manik tidak lepas."},
   {"urutan":2,"teks":"Masukkan satu manik sambil {nama} melihat."},
   {"urutan":3,"teks":"Berikan tali dan manik kepada {nama}."},
   {"urutan":4,"teks":"Bantu hanya memegang tali jika ia kesulitan."},
   {"urutan":5,"teks":"Ikat menjadi gelang setelah delapan manik."}]',
 'Pakai manik berlubang lebih besar dan tali yang lebih kaku.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('motorik', 4, 'Menirukan lima gerakan berurutan',
 'Melatih {nama} mengingat dan mengulang rangkaian gerakan.',
 20, '{"Ruang kosong"}',
 '[{"urutan":1,"teks":"Lakukan dua gerakan sederhana berurutan, misalnya tepuk lalu putar."},
   {"urutan":2,"teks":"Ajak {nama} menirukan."},
   {"urutan":3,"teks":"Tambah satu gerakan setiap kali ia berhasil."},
   {"urutan":4,"teks":"Berhenti di lima gerakan, lalu tukar peran."}]',
 'Kurangi menjadi dua gerakan dan lakukan lebih lambat.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

-- ============================================================== SENSORIK ==

('sensorik', 1, 'Meraba tiga tekstur kain',
 'Memberi {nama} pengalaman raba yang dapat ia terima dengan tenang.',
 6, '{"Handuk","Kain katun","Kain licin"}',
 '[{"urutan":1,"teks":"Letakkan tiga kain berjajar di atas meja."},
   {"urutan":2,"teks":"Sentuh satu kain dengan punggung tangan Anda."},
   {"urutan":3,"teks":"Biarkan {nama} menyentuh yang ia pilih, tanpa diarahkan."},
   {"urutan":4,"teks":"Hentikan segera jika {nama} menarik tangannya."}]',
 'Sediakan dua kain saja dan mulai dari yang paling ia kenal.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('sensorik', 1, 'Bermain beras dalam baskom',
 'Memberi {nama} rangsang raba yang dapat ia atur sendiri takarannya.',
 8, '{"Beras","Baskom","Gelas plastik"}',
 '[{"urutan":1,"teks":"Isi baskom dengan beras setinggi dua jari."},
   {"urutan":2,"teks":"Letakkan gelas di dalamnya."},
   {"urutan":3,"teks":"Biarkan {nama} menyendok dan menuang sesukanya."},
   {"urutan":4,"teks":"Akhiri saat perhatiannya beralih, bukan saat waktunya habis."}]',
 'Sediakan sendok agar {nama} tidak perlu menyentuh beras langsung.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('sensorik', 1, 'Mendengarkan tiga bunyi rumah tangga',
 'Melatih {nama} memperhatikan bunyi satu per satu, bukan sekaligus.',
 6, '{"Sendok","Gelas","Kertas"}',
 '[{"urutan":1,"teks":"Pastikan ruangan sedang sepi."},
   {"urutan":2,"teks":"Bunyikan satu benda dengan pelan."},
   {"urutan":3,"teks":"Diam sepuluh detik sebelum bunyi berikutnya."},
   {"urutan":4,"teks":"Berhenti jika {nama} menutup telinga."}]',
 'Turunkan volume bunyi dan perpanjang jeda menjadi lima belas detik.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('sensorik', 2, 'Mencari benda tersembunyi dalam beras',
 'Melatih {nama} mengenali bentuk melalui rabaan sambil tangannya sibuk.',
 10, '{"Beras","Baskom","Tiga benda kecil"}',
 '[{"urutan":1,"teks":"Kubur tiga benda di dalam beras sambil {nama} melihat."},
   {"urutan":2,"teks":"Minta {nama} mencari satu benda."},
   {"urutan":3,"teks":"Tunggu tanpa memberi petunjuk arah."},
   {"urutan":4,"teks":"Ulangi sampai ketiganya ditemukan."}]',
 'Kubur benda lebih dangkal dan kurangi menjadi dua benda.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('sensorik', 2, 'Menebak benda di dalam kantong kain',
 'Melatih {nama} mengenali benda tanpa melihatnya, dengan kendali penuh di tangannya.',
 10, '{"Kantong kain","Tiga benda yang dikenal"}',
 '[{"urutan":1,"teks":"Perlihatkan ketiga benda kepada {nama} lebih dulu."},
   {"urutan":2,"teks":"Masukkan satu benda ke kantong tanpa ia lihat."},
   {"urutan":3,"teks":"Biarkan {nama} meraba dari luar atau memasukkan tangan, sesuai pilihannya."},
   {"urutan":4,"teks":"Buka kantong dan cocokkan bersama."}]',
 'Pakai kantong berbahan tipis agar bentuknya terasa dari luar.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('sensorik', 2, 'Memijat lembut telapak tangan dengan bola',
 'Memberi {nama} tekanan lembut yang dapat ia hentikan kapan saja.',
 10, '{"Bola karet kecil"}',
 '[{"urutan":1,"teks":"Tunjukkan bolanya dan tanyakan boleh atau tidak."},
   {"urutan":2,"teks":"Gulirkan bola di telapak tangan {nama} dengan tekanan ringan."},
   {"urutan":3,"teks":"Berhenti setiap sepuluh detik dan tunggu ia meminta lanjut."},
   {"urutan":4,"teks":"Akhiri segera jika ia menarik tangan atau diam."}]',
 'Kurangi tekanan dan lakukan di atas lengan baju, bukan kulit langsung.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('sensorik', 3, 'Membedakan tiga aroma dapur',
 'Melatih {nama} memperhatikan perbedaan aroma yang lembut.',
 14, '{"Kulit jeruk","Daun teh","Kayu manis"}',
 '[{"urutan":1,"teks":"Letakkan ketiganya di piring terpisah."},
   {"urutan":2,"teks":"Dekatkan satu piring sejauh satu jengkal dari {nama}."},
   {"urutan":3,"teks":"Biarkan ia mendekat sendiri jika mau."},
   {"urutan":4,"teks":"Beri jeda satu menit antar aroma."},
   {"urutan":5,"teks":"Hentikan jika {nama} memalingkan wajah."}]',
 'Pakai satu aroma saja per sesi dan jauhkan jaraknya.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('sensorik', 3, 'Berjalan di atas tiga alas berbeda',
 'Melatih {nama} menerima rangsang berbeda pada telapak kaki.',
 14, '{"Handuk","Keset","Lantai kosong"}',
 '[{"urutan":1,"teks":"Susun ketiga alas berjajar."},
   {"urutan":2,"teks":"Berjalan melewatinya satu kali sambil {nama} melihat."},
   {"urutan":3,"teks":"Ajak {nama} berjalan sambil berpegangan jika ia mau."},
   {"urutan":4,"teks":"Biarkan ia melewati alas yang tidak nyaman tanpa dipaksa."}]',
 'Kurangi menjadi dua alas dan izinkan tetap memakai kaus kaki.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('sensorik', 3, 'Mengatur suara keras sedang dan pelan',
 'Melatih {nama} mengenali dan memilih tingkat suara.',
 15, '{"Tiga kartu bergambar","Suara sendiri"}',
 '[{"urutan":1,"teks":"Buat tiga kartu: pelan, sedang, keras."},
   {"urutan":2,"teks":"Ucapkan satu kata dengan tiga tingkat suara sambil menunjuk kartunya."},
   {"urutan":3,"teks":"Minta {nama} memilih kartu, lalu Anda mengikuti."},
   {"urutan":4,"teks":"Tukar peran di putaran berikutnya."}]',
 'Hilangkan tingkat keras dan berlatih pelan dan sedang saja.',
 '{kalimat_pendek,lancar}'),

('sensorik', 4, 'Memilih tempat lebih tenang saat suara meningkat',
 'Melatih {nama} mengenali ketidaknyamanan dan memilih jalan keluarnya sendiri.',
 18, '{"Dua ruangan berbeda"}',
 '[{"urutan":1,"teks":"Sepakati lebih dulu ruangan mana yang menjadi tempat tenang."},
   {"urutan":2,"teks":"Saat rumah mulai ramai, tanyakan apakah {nama} ingin pindah."},
   {"urutan":3,"teks":"Antar tanpa berkomentar jika ia memilih pindah."},
   {"urutan":4,"teks":"Kembali bersama saat ia siap, tanpa ditanya alasannya."}]',
 'Tentukan tempat tenang di ruangan yang paling dekat dan paling dikenal.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('sensorik', 4, 'Menyiapkan sudut istirahat sendiri',
 'Melatih {nama} menyiapkan tempat yang membuatnya nyaman tanpa diarahkan.',
 18, '{"Bantal","Selimut","Kotak"}',
 '[{"urutan":1,"teks":"Tunjukkan sudut ruangan yang bisa dipakai {nama}."},
   {"urutan":2,"teks":"Sediakan tiga benda dan biarkan ia memilih."},
   {"urutan":3,"teks":"Biarkan {nama} menata sesuka hatinya."},
   {"urutan":4,"teks":"Sepakati bahwa sudut itu miliknya dan tidak dibongkar."}]',
 'Siapkan sudutnya bersama-sama dan mulai dengan satu benda saja.',
 '{kalimat_pendek,lancar}'),

('sensorik', 4, 'Menandai tingkat kenyamanan dengan kartu',
 'Melatih {nama} menyampaikan kondisinya sebelum menjadi kewalahan.',
 20, '{"Tiga kartu warna berbeda","Spidol"}',
 '[{"urutan":1,"teks":"Buat tiga kartu bersama {nama}: nyaman, mulai berat, ingin berhenti."},
   {"urutan":2,"teks":"Tempel kartunya di tempat yang mudah ia jangkau."},
   {"urutan":3,"teks":"Tanyakan kartu mana yang cocok pada dua waktu berbeda hari ini."},
   {"urutan":4,"teks":"Hentikan kegiatan segera saat ia memilih kartu ingin berhenti."},
   {"urutan":5,"teks":"Ucapkan terima kasih karena ia memberi tahu."}]',
 'Kurangi menjadi dua kartu: masih nyaman dan ingin berhenti.',
 '{kalimat_pendek,lancar}'),

-- =========================================================== KEMANDIRIAN ==

('kemandirian', 1, 'Menaruh sepatu di rak setelah pulang',
 'Melatih {nama} menyelesaikan satu langkah rutinitas pulang tanpa diingatkan.',
 5, '{"Rak sepatu"}',
 '[{"urutan":1,"teks":"Letakkan rak sepatu tepat di dekat pintu."},
   {"urutan":2,"teks":"Taruh sepatu Anda lebih dulu sambil {nama} melihat."},
   {"urutan":3,"teks":"Tunggu tanpa mengingatkan."},
   {"urutan":4,"teks":"Bantu satu sepatu jika ia belum bergerak setelah sepuluh detik."}]',
 'Beri tanda gambar di rak agar tempat sepatunya terlihat jelas.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 1, 'Membuang bungkus ke tempat sampah',
 'Melatih {nama} menyelesaikan kegiatan makan dengan satu langkah beres-beres.',
 5, '{"Tempat sampah"}',
 '[{"urutan":1,"teks":"Pastikan tempat sampah terlihat dari tempat {nama} duduk."},
   {"urutan":2,"teks":"Setelah camilan habis, tunjuk tempat sampahnya."},
   {"urutan":3,"teks":"Tunggu {nama} berdiri sendiri."},
   {"urutan":4,"teks":"Berjalan bersama jika ia ragu."}]',
 'Pindahkan tempat sampah lebih dekat, sejauh satu langkah.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 1, 'Menggantung handuk sendiri',
 'Melatih {nama} menyimpan barangnya di tempat yang tetap.',
 6, '{"Handuk","Gantungan setinggi anak"}',
 '[{"urutan":1,"teks":"Pasang gantungan setinggi dada {nama}."},
   {"urutan":2,"teks":"Gantung handuk Anda lebih dulu."},
   {"urutan":3,"teks":"Berikan handuknya dan tunggu."},
   {"urutan":4,"teks":"Terima hasilnya walau belum rapi."}]',
 'Turunkan gantungan dan pakai handuk yang lebih kecil.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 2, 'Memakai kaus kaki sendiri',
 'Melatih {nama} menyelesaikan langkah berpakaian yang paling mudah dikuasai.',
 10, '{"Kaus kaki longgar","Kursi"}',
 '[{"urutan":1,"teks":"Duduk berdampingan di kursi."},
   {"urutan":2,"teks":"Masukkan ujung kaus kaki ke jari kaki {nama}."},
   {"urutan":3,"teks":"Biarkan ia menarik sisanya sendiri."},
   {"urutan":4,"teks":"Kurangi bantuan Anda sedikit demi sedikit tiap hari."}]',
 'Pakai kaus kaki yang lebih longgar dan lebih pendek.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 2, 'Menuang sereal ke mangkuk',
 'Melatih {nama} menyiapkan sebagian sarapannya sendiri.',
 10, '{"Sereal dalam wadah kecil","Mangkuk","Nampan"}',
 '[{"urutan":1,"teks":"Pindahkan sereal ke wadah kecil yang ringan."},
   {"urutan":2,"teks":"Letakkan mangkuk di atas nampan."},
   {"urutan":3,"teks":"Biarkan {nama} menuang sampai ia berhenti sendiri."},
   {"urutan":4,"teks":"Bereskan tumpahan bersama tanpa berkomentar."}]',
 'Kurangi isi wadah agar lebih ringan diangkat.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 2, 'Menyikat gigi mengikuti tiga langkah',
 'Melatih {nama} mengikuti urutan tetap pada rutinitas harian.',
 12, '{"Sikat gigi","Pasta gigi","Kartu bergambar"}',
 '[{"urutan":1,"teks":"Tempel tiga kartu di cermin: basahi, sikat, kumur."},
   {"urutan":2,"teks":"Tunjuk kartu pertama dan tunggu."},
   {"urutan":3,"teks":"Lanjut ke kartu berikutnya hanya setelah langkah itu selesai."},
   {"urutan":4,"teks":"Akhiri dengan mencentang ketiga kartu bersama."}]',
 'Kurangi menjadi dua kartu dan lakukan bersama di depan cermin.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 3, 'Menyiapkan tas sekolah dari daftar bergambar',
 'Melatih {nama} memeriksa kelengkapan barangnya sendiri.',
 14, '{"Tas","Daftar bergambar","Barang sekolah"}',
 '[{"urutan":1,"teks":"Buat daftar bergambar berisi empat barang."},
   {"urutan":2,"teks":"Letakkan semua barang di lantai bersama tasnya."},
   {"urutan":3,"teks":"Biarkan {nama} memasukkan satu per satu sambil menunjuk daftar."},
   {"urutan":4,"teks":"Periksa ulang bersama di akhir."}]',
 'Kurangi daftar menjadi dua barang dan singkirkan barang lain dari lantai.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 3, 'Mengancingkan baju dari bawah ke atas',
 'Melatih ketelitian jari {nama} pada urutan yang selalu sama.',
 15, '{"Baju berkancing besar"}',
 '[{"urutan":1,"teks":"Letakkan baju di meja, bukan di badan."},
   {"urutan":2,"teks":"Kancingkan yang paling bawah bersama-sama."},
   {"urutan":3,"teks":"Biarkan {nama} melanjutkan ke atas."},
   {"urutan":4,"teks":"Berhenti setelah tiga kancing walau belum semua."}]',
 'Pakai baju dengan kancing lebih besar dan lubang lebih longgar.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 3, 'Merapikan tempat tidur sendiri',
 'Melatih {nama} menyelesaikan rutinitas pagi tanpa diarahkan langkah demi langkah.',
 14, '{"Selimut","Bantal"}',
 '[{"urutan":1,"teks":"Tarik selimut sampai setengah bersama-sama."},
   {"urutan":2,"teks":"Biarkan {nama} menarik sisanya."},
   {"urutan":3,"teks":"Minta ia meletakkan bantal di tempatnya."},
   {"urutan":4,"teks":"Lihat hasilnya bersama tanpa merapikan ulang."}]',
 'Kurangi menjadi satu langkah saja: meletakkan bantal.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 4, 'Menjalankan rutinitas pagi dari kartu urutan',
 'Melatih {nama} menjalankan beberapa langkah berurutan tanpa diingatkan.',
 20, '{"Lima kartu bergambar","Penjepit"}',
 '[{"urutan":1,"teks":"Susun lima kartu sesuai urutan pagi {nama}."},
   {"urutan":2,"teks":"Gantung kartunya di tempat yang ia lewati."},
   {"urutan":3,"teks":"Biarkan {nama} membalik kartu setiap langkah selesai."},
   {"urutan":4,"teks":"Jangan mengingatkan sebelum ia berhenti lebih dari satu menit."},
   {"urutan":5,"teks":"Lihat kartu yang sudah dibalik bersama di akhir."}]',
 'Kurangi menjadi tiga kartu dan gantung di satu tempat saja.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 4, 'Menyiapkan roti isi sendiri',
 'Melatih {nama} menyelesaikan beberapa langkah menyiapkan makanan.',
 18, '{"Roti","Isian siap pakai","Piring","Pisau tumpul"}',
 '[{"urutan":1,"teks":"Siapkan semua bahan di satu nampan lebih dulu."},
   {"urutan":2,"teks":"Sebutkan urutannya sekali, lalu mundur satu langkah."},
   {"urutan":3,"teks":"Biarkan {nama} mengerjakan dengan caranya."},
   {"urutan":4,"teks":"Makan bersama tanpa mengomentari bentuknya."}]',
 'Kurangi menjadi dua bahan dan siapkan isian yang sudah dioles.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('kemandirian', 4, 'Memilih pakaian sesuai cuaca',
 'Melatih {nama} mengambil keputusan berdasarkan yang ia amati.',
 18, '{"Dua setel pakaian","Jendela"}',
 '[{"urutan":1,"teks":"Ajak {nama} melihat ke luar jendela."},
   {"urutan":2,"teks":"Tunjukkan dua setel pakaian yang berbeda ketebalannya."},
   {"urutan":3,"teks":"Tanyakan mana yang cocok hari ini."},
   {"urutan":4,"teks":"Terima pilihannya, dan bahas kembali di sore hari."}]',
 'Sediakan dua pilihan yang jelas berbeda, misalnya lengan pendek dan jaket.',
 '{kalimat_pendek,lancar}'),

-- ================================================================ SOSIAL ==

('sosial', 1, 'Duduk berdampingan saat menyusun balok',
 'Membiasakan {nama} berada dekat orang lain tanpa tuntutan berinteraksi.',
 6, '{"Balok atau kotak kecil"}',
 '[{"urutan":1,"teks":"Duduk di sebelah {nama}, bukan di hadapannya."},
   {"urutan":2,"teks":"Susun balok Anda sendiri tanpa mengajak bicara."},
   {"urutan":3,"teks":"Biarkan {nama} menyusun dengan caranya."},
   {"urutan":4,"teks":"Akhiri sebelum ia menjauh sendiri."}]',
 'Duduk sedikit lebih jauh dan sediakan dua tumpuk balok terpisah.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('sosial', 1, 'Memberi benda saat diminta',
 'Melatih {nama} menanggapi permintaan orang lain dengan gerakan.',
 6, '{"Tiga benda kecil","Mangkuk"}',
 '[{"urutan":1,"teks":"Letakkan tiga benda di antara Anda dan {nama}."},
   {"urutan":2,"teks":"Tengadahkan telapak tangan dan tunggu."},
   {"urutan":3,"teks":"Sebutkan nama bendanya sekali jika ia belum bergerak."},
   {"urutan":4,"teks":"Terima benda apa pun yang ia berikan."}]',
 'Kurangi menjadi satu benda dan dekatkan ke tangan {nama}.',
 '{belum_verbal,beberapa_kata}'),

('sosial', 1, 'Melambaikan tangan saat berpisah',
 'Melatih {nama} memakai satu isyarat sosial yang selalu sama.',
 5, '{"Pintu"}',
 '[{"urutan":1,"teks":"Berhenti di pintu dan hadapkan wajah ke {nama}."},
   {"urutan":2,"teks":"Lambaikan tangan satu kali."},
   {"urutan":3,"teks":"Tunggu tiga detik sebelum pergi."},
   {"urutan":4,"teks":"Lakukan sama persis setiap kali berpisah."}]',
 'Pegang tangan {nama} dan lambaikan bersama pada beberapa hari pertama.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('sosial', 2, 'Bergiliran menggelindingkan bola',
 'Melatih {nama} menunggu giliran dalam kegiatan yang jelas ritmenya.',
 10, '{"Bola plastik"}',
 '[{"urutan":1,"teks":"Duduk berhadapan di lantai dengan kaki terbuka."},
   {"urutan":2,"teks":"Gelindingkan bola ke arah {nama}."},
   {"urutan":3,"teks":"Tunggu ia mengembalikan tanpa meminta."},
   {"urutan":4,"teks":"Ulangi sepuluh kali dengan ritme yang tetap."}]',
 'Perpendek jarak duduk dan pakai bola yang lebih besar.',
 '{belum_verbal,beberapa_kata,kalimat_pendek,lancar}'),

('sosial', 2, 'Menunggu giliran dengan kartu antre',
 'Melatih {nama} melihat kapan gilirannya tiba tanpa harus diberi tahu.',
 12, '{"Dua kartu bergambar","Mainan yang disukai"}',
 '[{"urutan":1,"teks":"Buat dua kartu: giliran Anda dan giliran {nama}."},
   {"urutan":2,"teks":"Letakkan kartu giliran Anda di depan saat Anda bermain."},
   {"urutan":3,"teks":"Tukar kartunya saat giliran berpindah."},
   {"urutan":4,"teks":"Buat giliran Anda singkat, tidak lebih dari sepuluh detik."}]',
 'Perpendek giliran Anda menjadi lima detik dan pakai kartu berukuran besar.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('sosial', 2, 'Menyapa satu orang di rumah',
 'Melatih {nama} memulai kontak dengan orang yang sudah ia kenal.',
 10, '{"Anggota keluarga"}',
 '[{"urutan":1,"teks":"Pilih satu orang yang paling sering {nama} temui."},
   {"urutan":2,"teks":"Dekati bersama-sama dan berhenti sejauh dua langkah."},
   {"urutan":3,"teks":"Sapa lebih dulu, lalu tunggu."},
   {"urutan":4,"teks":"Terima sapaan dalam bentuk apa pun, termasuk melirik."}]',
 'Lakukan saat rumah sedang sepi dan hanya ada satu orang lain.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('sosial', 3, 'Bermain tebak gerakan berdua',
 'Melatih {nama} memperhatikan orang lain untuk mengetahui maksudnya.',
 14, '{"Ruang kosong"}',
 '[{"urutan":1,"teks":"Peragakan satu kegiatan sehari-hari tanpa suara."},
   {"urutan":2,"teks":"Tunggu {nama} menebak."},
   {"urutan":3,"teks":"Tukar peran dan tebak peragaan {nama}."},
   {"urutan":4,"teks":"Mainkan empat putaran, lalu berhenti."}]',
 'Pakai gerakan yang sangat dikenal, misalnya makan atau tidur.',
 '{kalimat_pendek,lancar}'),

('sosial', 3, 'Meminjam mainan dengan kalimat',
 'Melatih {nama} meminta izin sebelum mengambil barang orang lain.',
 14, '{"Dua mainan"}',
 '[{"urutan":1,"teks":"Pegang satu mainan yang {nama} inginkan."},
   {"urutan":2,"teks":"Tunggu ia mendekat."},
   {"urutan":3,"teks":"Ucapkan contoh kalimat pinjam satu kali, lalu diam."},
   {"urutan":4,"teks":"Berikan segera setelah ia meminta dengan cara apa pun."},
   {"urutan":5,"teks":"Tukar peran agar {nama} juga yang meminjamkan."}]',
 'Berikan mainan setelah usaha pertama, tanpa menunggu kalimat lengkap.',
 '{kalimat_pendek,lancar}'),

('sosial', 3, 'Menyelesaikan puzzle bersama',
 'Melatih {nama} mengerjakan satu tujuan bersama orang lain.',
 15, '{"Puzzle sederhana"}',
 '[{"urutan":1,"teks":"Bagi kepingan menjadi dua bagian yang sama banyak."},
   {"urutan":2,"teks":"Pasang satu keping bergantian."},
   {"urutan":3,"teks":"Tunggu giliran {nama} tanpa memasangkan untuknya."},
   {"urutan":4,"teks":"Lihat hasilnya bersama saat selesai."}]',
 'Pakai puzzle dengan kepingan lebih sedikit dan lebih besar.',
 '{beberapa_kata,kalimat_pendek,lancar}'),

('sosial', 4, 'Mengajak bermain dengan satu ajakan',
 'Melatih {nama} memulai kegiatan bersama, bukan hanya menunggu diajak.',
 18, '{"Dua permainan pilihan"}',
 '[{"urutan":1,"teks":"Duduk di ruangan yang sama sambil mengerjakan hal lain."},
   {"urutan":2,"teks":"Tunggu {nama} mendekat tanpa Anda memulai."},
   {"urutan":3,"teks":"Jika sepuluh menit berlalu, tunjukkan dua permainan tanpa bicara."},
   {"urutan":4,"teks":"Ikuti ajakan {nama} apa pun bentuknya."}]',
 'Letakkan permainan di dekat {nama} sejak awal agar ajakannya lebih mudah.',
 '{kalimat_pendek,lancar}'),

('sosial', 4, 'Bergiliran memilih permainan',
 'Melatih {nama} menerima pilihan orang lain sesekali.',
 18, '{"Tiga permainan","Kartu urutan"}',
 '[{"urutan":1,"teks":"Sepakati bahwa masing-masing memilih satu kali."},
   {"urutan":2,"teks":"Biarkan {nama} memilih lebih dulu."},
   {"urutan":3,"teks":"Mainkan pilihannya sampai selesai."},
   {"urutan":4,"teks":"Giliran Anda memilih, dan mainkan sama lamanya."},
   {"urutan":5,"teks":"Akhiri dengan pilihan {nama} lagi."}]',
 'Kurangi menjadi dua permainan dan perpendek durasi tiap giliran.',
 '{kalimat_pendek,lancar}'),

('sosial', 4, 'Menanyakan kabar teman atau saudara',
 'Melatih {nama} menunjukkan perhatian kepada orang lain lewat pertanyaan.',
 20, '{"Telepon atau tatap muka"}',
 '[{"urutan":1,"teks":"Pilih satu orang yang {nama} kenal baik."},
   {"urutan":2,"teks":"Sepakati satu pertanyaan yang akan ia ajukan."},
   {"urutan":3,"teks":"Mulai percakapan, lalu berikan giliran kepada {nama}."},
   {"urutan":4,"teks":"Biarkan percakapan berhenti kapan pun ia ingin."}]',
 'Lakukan lewat pesan suara singkat lebih dulu, bukan percakapan langsung.',
 '{lancar}')

on conflict (kategori, tingkat, judul) do nothing;
